// <auto-generated />
using System;
using Application.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application.Migrations
{
    [DbContext(typeof(DatabaseModel))]
    partial class DatabaseModelModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Application.Models.Activities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("TrainingId");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Application.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Flat");

                    b.Property<string>("Postcode");

                    b.Property<string>("Street");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Application.Models.Attendance", b =>
                {
                    b.Property<string>("PlayerSRU");

                    b.Property<int>("TrainingId");

                    b.HasKey("PlayerSRU", "TrainingId");

                    b.HasIndex("PlayerSRU")
                        .IsUnique();

                    b.HasIndex("TrainingId")
                        .IsUnique();

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("Application.Models.Doctor", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("PlayerSRU");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.HasIndex("PlayerSRU")
                        .IsUnique();

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("Application.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<DateTime>("KO");

                    b.Property<int>("Location");

                    b.Property<string>("Opposition");

                    b.Property<int>("Result");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Application.Models.Guardian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("JuniorSRU");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Relationship");

                    b.Property<DateTime?>("Signature");

                    b.HasKey("Id");

                    b.HasIndex("JuniorSRU");

                    b.ToTable("Guardian");
                });

            modelBuilder.Entity("Application.Models.HealthIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("PlayerSRU");

                    b.HasKey("Id");

                    b.HasIndex("PlayerSRU");

                    b.ToTable("HealthIssue");
                });

            modelBuilder.Entity("Application.Models.Junior", b =>
                {
                    b.Property<string>("SRU");

                    b.HasKey("SRU");

                    b.ToTable("Junior");
                });

            modelBuilder.Entity("Application.Models.Kin", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Relationship");

                    b.Property<string>("SeniorSRU");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.HasIndex("SeniorSRU")
                        .IsUnique();

                    b.ToTable("Kin");
                });

            modelBuilder.Entity("Application.Models.Member", b =>
                {
                    b.Property<string>("SRU");

                    b.Property<bool>("Active");

                    b.Property<int?>("AddressId");

                    b.Property<string>("Email");

                    b.Property<string>("Mobile");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Surname");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("SRU");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Application.Models.Player", b =>
                {
                    b.Property<string>("SRU");

                    b.Property<int>("Position");

                    b.HasKey("SRU");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Application.Models.Profile", b =>
                {
                    b.Property<string>("PlayerSRU");

                    b.Property<int>("SkillId");

                    b.Property<string>("Description");

                    b.Property<int>("Score");

                    b.HasKey("PlayerSRU", "SkillId");

                    b.HasIndex("PlayerSRU")
                        .IsUnique();

                    b.HasIndex("SkillId")
                        .IsUnique();

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("Application.Models.Scores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<int?>("GameId");

                    b.Property<int>("Half");

                    b.Property<int>("Points");

                    b.Property<int>("Team");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Application.Models.Senior", b =>
                {
                    b.Property<string>("SRU");

                    b.HasKey("SRU");

                    b.ToTable("Senior");
                });

            modelBuilder.Entity("Application.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Evaluable");

                    b.Property<string>("Name");

                    b.Property<int?>("PartentId");

                    b.HasKey("Id");

                    b.HasIndex("PartentId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("Application.Models.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CoachSRU");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Location");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.HasIndex("CoachSRU");

                    b.ToTable("Training");
                });

            modelBuilder.Entity("Application.Models.Activities", b =>
                {
                    b.HasOne("Application.Models.Training", "Training")
                        .WithMany("Activitieses")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Application.Models.Attendance", b =>
                {
                    b.HasOne("Application.Models.Player", "Player")
                        .WithOne()
                        .HasForeignKey("Application.Models.Attendance", "PlayerSRU")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Application.Models.Training", "Training")
                        .WithOne()
                        .HasForeignKey("Application.Models.Attendance", "TrainingId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Application.Models.Doctor", b =>
                {
                    b.HasOne("Application.Models.Address", "Address")
                        .WithOne()
                        .HasForeignKey("Application.Models.Doctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Application.Models.Player", "Player")
                        .WithOne("Doctor")
                        .HasForeignKey("Application.Models.Doctor", "PlayerSRU");
                });

            modelBuilder.Entity("Application.Models.Guardian", b =>
                {
                    b.HasOne("Application.Models.Junior", "Junior")
                        .WithMany("Guardians")
                        .HasForeignKey("JuniorSRU")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Application.Models.HealthIssue", b =>
                {
                    b.HasOne("Application.Models.Player", "Player")
                        .WithMany("HealthIssues")
                        .HasForeignKey("PlayerSRU")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Application.Models.Junior", b =>
                {
                    b.HasOne("Application.Models.Player", "Player")
                        .WithOne("Junior")
                        .HasForeignKey("Application.Models.Junior", "SRU")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Application.Models.Kin", b =>
                {
                    b.HasOne("Application.Models.Address", "Address")
                        .WithOne()
                        .HasForeignKey("Application.Models.Kin", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Application.Models.Senior", "Senior")
                        .WithOne("Kin")
                        .HasForeignKey("Application.Models.Kin", "SeniorSRU");
                });

            modelBuilder.Entity("Application.Models.Member", b =>
                {
                    b.HasOne("Application.Models.Address", "Address")
                        .WithOne()
                        .HasForeignKey("Application.Models.Member", "AddressId");
                });

            modelBuilder.Entity("Application.Models.Player", b =>
                {
                    b.HasOne("Application.Models.Member", "Member")
                        .WithOne("Player")
                        .HasForeignKey("Application.Models.Player", "SRU")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Application.Models.Profile", b =>
                {
                    b.HasOne("Application.Models.Player", "Player")
                        .WithOne()
                        .HasForeignKey("Application.Models.Profile", "PlayerSRU")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Application.Models.Skill", "Skill")
                        .WithOne()
                        .HasForeignKey("Application.Models.Profile", "SkillId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Application.Models.Scores", b =>
                {
                    b.HasOne("Application.Models.Game")
                        .WithMany("Scores")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Application.Models.Senior", b =>
                {
                    b.HasOne("Application.Models.Player", "Player")
                        .WithOne("Senior")
                        .HasForeignKey("Application.Models.Senior", "SRU")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Application.Models.Skill", b =>
                {
                    b.HasOne("Application.Models.Skill", "Partent")
                        .WithMany()
                        .HasForeignKey("PartentId");
                });

            modelBuilder.Entity("Application.Models.Training", b =>
                {
                    b.HasOne("Application.Models.Member", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachSRU");
                });
#pragma warning restore 612, 618
        }
    }
}
